# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI-CD-Pipeline-Inspire-Offices

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Code ophalen uit repository
        uses: actions/checkout@v4

      - name: Controleer Docker Compose structuur
        run: docker compose config

      - name: Bouw de Docker Image (Fase 2 Validatie)
        run: docker compose build
      
      # Zet de builder aan voor de push-actie
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
# --- FASE 2 PREPARATION: Security Scan (Aanbevolen in Risicoanalyse) ---
    # - name: Run Trivy vulnerability scanner
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     image-ref: 'necatiemir/pipeline_inspire:latest'
    #     format: 'table'
    #     exit-code: '1' # Zorgt ervoor dat de pijplijn stopt bij een High/Critical lek
    # -----------------------------------------------------------------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: necatiemir/pipeline_inspire:latest
